# Generated by Django 6.0 on 2025-12-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_brand_product_model_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='About_This_Item',
        ),
    ]
