# Generated by Django 6.0 on 2025-12-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_description_product_about_this_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='About_This_Item',
        ),
        migrations.AddField(
            model_name='product',
            name='about_this_item',
            field=models.TextField(blank=True, null=True),
        ),
    ]
