# Generated by Django 6.0 on 2025-12-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_care_instructions_product_country_of_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_limited_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
